### ISSUE TITLE
Usage without plain-text priv-keys

### ISSUE THREAD

**Issue by maurelian** [colinnielsen/safe-tools#9]
Hi there, 

I'm curious if there's a reason that there is no version of [`_setupSafe()`](https://github.com/colinnielsen/safe-tools/blob/ce6c654a76d91b619ab7778c77d1a76b3ced6666/src/SafeTestTools.sol#L307) that accepts addresses instead of private keys, is this intentional or just not something that's been incorporated yet?

**Comment by colinnielsen** [comment]
> Hi there,
> 
> I'm curious if there's a reason that there is no version of [`_setupSafe()`](https://github.com/colinnielsen/safe-tools/blob/ce6c654a76d91b619ab7778c77d1a76b3ced6666/src/SafeTestTools.sol#L307) that accepts addresses instead of private keys, is this intentional or just not something that's been incorporated yet?

Working on this now :)

**Comment by colinnielsen** [comment]
@maurelian This is released in v0.3.0
